name: Build QMK (Keyball61 VIA)

on:
  push:
    paths:
      - "qmk_firmware/**"
      - ".github/workflows/qmk-build.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip gcc-avr binutils-avr avr-libc zip
          python3 -m pip install --upgrade pip
          pip3 install qmk

      - name: QMK setup
        working-directory: qmk_firmware
        run: |
          qmk setup -y --home "$GITHUB_WORKSPACE/qmk_firmware"
          qmk doctor || true

      - name: Build Keyball61 VIA
        working-directory: qmk_firmware
        run: |
          qmk compile -kb keyball/keyball61 -km via

      - name: Upload HEX
        uses: actions/upload-artifact@v4
        with:
          name: keyball61-via-hex
          path: |
            qmk_firmware/.build/*keyball61*_via.hex
